# Generated by Django 5.1.3 on 2025-01-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalfavoriterecipe_historicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='file_reward',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Награды, дипломы'),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='social_networks',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылки на социальные сети'),
        ),
        migrations.AddField(
            model_name='profile',
            name='file_reward',
            field=models.FileField(blank=True, null=True, upload_to='files_of_awards', verbose_name='Награды, дипломы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_networks',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылки на социальные сети'),
        ),
    ]
