# Generated by Django 5.1.3 on 2024-11-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_number'], 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='recipes.RecIng', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
