# Generated by Django 5.1.3 on 2024-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recing',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recing',
            name='unit',
            field=models.CharField(choices=[('л', 'Литр'), ('мл', 'Миллилитр'), ('ст', 'Стакан'), ('ст. л', 'Столовая ложка'), ('ч. л', 'Чайная ложка'), ('шт', 'Штук'), ('гр', 'Грамм'), ('кг', 'Килограмм'), ('вкус.', 'По вкусу')], max_length=5, verbose_name='Единица измерения'),
        ),
    ]
