# Generated by Django 5.1.3 on 2024-12-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recing_quantity_alter_recing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
