# Generated by Django 5.1.3 on 2024-12-07 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
