# Generated by Django 5.1.3 on 2024-12-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_historicalcategory_historicalingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecipe',
            name='main_photo',
            field=models.TextField(blank=True, max_length=100, verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='recipes/main_photos', verbose_name='Основное фото'),
        ),
    ]
